[build]
publish = "."
command = "echo ✅ OpenVerse RSS Build Successful"

[[redirects]]
  from = "/rss/english/*"
  to = "/rss/english/:splat"
  status = 200

[[redirects]]
  from = "/rss/spanish/*"
  to = "/rss/spanish/:splat"
  status = 200
