[build]
publish = "rss-deploy/rss"
command = "echo ✅ OpenVerse RSS build started..."

[context.production.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/"
  to = "/rss/english/podcast.xml"
  status = 301

[[headers]]
  for = "/rss/*"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=0, must-revalidate"
